### PR TITLE
enhance/enable backlink toggle

### PR DESCRIPTION
**Pull request by kevinslin**
enhance(publish): add configuration to disable backlinks, both across the workspace and on a per note level

- we add `enableBackLinks` in two places:
  - inside `dendron.yml` in `publishing` namespace
  - inside individual notes in `config.global` namespace
- NOTE: despite `enableBackLinks` existing in only `publishing`, it also applies to the preview because both the preview and publishing have the same unified desitnation `HTML` and we currently don't have a way of telling the two apart
  - there's more work to be done for fine tuning this for `preview`. this this isn't something that customers have asked for, we're going to save that work for a next phase
- NOTE: this change is necessary because of issues with backlinks in dendron published pages 

- this also adds a test workspace in `nextjs-tempalte` to facilitate easier testing of `nextjs`. a next item is to create playwright test based on the test workspace inside of `nextjst-template`
- this also refactors common-all so that `constants.ts` is moved under `constants/index.ts` and a bunch of sub exports are consolidated in one place
- this also updates `ci.yml` because of [[Changing File to Folder|dendron://dendron.docs/dev.process.code.gotchas.changing-file-to-folder]]

Docs: https://github.com/dendronhq/dendron-site/pull/425

***

# Dendron Extended PR Checklist

### Basics

- [x] code should follow [Code Conventions](dev.process.code)
- [x] circular dependency check: make sure your code is not introducing new circular dependencies in plugin-core.  See [Avoiding Circular Dependencies](dev.process.code.best-practices).
- [x] sticking to existing conventions instead of creating new ones 
  - eg: [if configuration for utilities are already in one module or package, add future utilities there as well](https://github.com/dendronhq/dendron/pull/1960#discussion_r786228021)

### Extended

- General
  - [x] check whether code be simplified
  - [x] check if similar function already exist in the codebase. if so, can it be re-used?
  - [x] check if this change adversely impact performance
- Operations
  - [x] when shipping this change, will it just work or will it introduce additional operational overhead due to complicated interface or known bugs?
- Architecture
  - [x] check if code is introducing changes on a foundational class or interface. if so, call for design review if needed 
    - eg: [making changes to DNode](https://github.com/dendronhq/dendron/pull/2158#pullrequestreview-854689586)

## Instrumentation

NA

### Basics

- [x] [Write Tests](dev.process.qa.test) 
- [x] [Confirm existing tests pass](dev.process.qa.test)
- [x] [Confirm manual testing](dev.process.qa.test) 
- [x] Common cases tested
- [x] 1-2 Edge cases tested
- [x] If your tests changes an existing snapshot, snapshots have been [updated](dev.process.qa.test)

### Extended

NA

### Basics

- [x] if your change reflects documentation changes, also submit a PR to [dendron-site](https://github.com/dendronhq/dendron-site) and mention the doc PR link in your current PR

## 

### Basics

- [~] does this change introduce a new or better way of doing things that others need to be aware of? if so, an async should be created and a process added in [Development](dev) or [Packages](pkg)

## 

### Extended

- [~]  is this a developer BREAKING change? if another person cloning from this branch will need to adjust their dependencies or mental model of the architecture, then it is. if this is the case, make sure this is communicated according to [Close Loop](dev.process.close-loop)
  - eg. [breaking dev change due to new dependency](https://github.com/dendronhq/dendron/pull/2188#pullrequestreview-855696330)

### CODE REVIEW

**Review by hikchoi — COMMENTED** [review]
> NOTE: despite enableBackLinks existing in only publishing, it also applies to the preview because both the preview and publishing have the same unified desitnation HTML and we currently don't have a way of telling the two apart

can't we check the ProcFlavor if it's PUBLISHING? (i.e. `MDUtilsV5.shouldApplyPublishingRules(proc)`)

> we add enableBackLinks in two places:
>   inside dendron.yml in publishing namespace
>   inside individual notes in config.global namespace

I mentioned this in https://github.com/dendronhq/dendron/pull/1979#discussion_r775388131 as well, (and it seems like enablePrettyRefs was also added as a note local config) but it's a bit confusing to introduce the global config namespace here for the purpose of per-note configurations.

1. Adding these to the global namespace would complicate things when we decide we want to actually use that namespace for what it was first intended to do (control a certain behavior in both preview and publishing).
1. It is semantically conflicting. 
    - According to the docs, here we are "overriding" the config (https://github.com/dendronhq/dendron-site/pull/425/files#diff-801bbfc119812e4eb022e2b9215f382bc8ecb3bbb721a81efdc91a436fe6aabbR13). There is no `global` namespace in `dendron.yml` to override. It's at this point just a proxy to let us enable per-note behavior.
    - Without full context that doing this is frontmatter is "overriding" a config, the current syntax is suggesting the opposite of what it is doing
        - we put `config.global.enableBackLinks: false` in frontmatter, but we are setting a note _local_ config.
        - this will naturally cause users to raise a question: _why is it called global?_
        - especially since we don't have a global namespace yet.

So these are the two concerns I have with the direction note local configs are going right now. Do you have plans to tackle this? Otherwise, the logic themselves look good.

**Comment by hikchoi** [comment]
I've also left a comment on the docs PR.

**Comment by kevinslin** [comment]
@hikchoi hear you on these concerns. this is why `enableChildLinks` was not formally documented and why this won't be either until we either release a `global` scope in `dendron.yml` or break out `preview` and `publishing` specific config. 

currently, we are doing this to hotfix certain elements of publishing (eg. backlinks on published pages with collections: https://www.kevinslin.com/notes/r4RrLx4xTM2Sc0yOouLkb/)

**Comment by hikchoi** [comment]
> @hikchoi hear you on these concerns. this is why `enableChildLinks` was not formally documented and why this won't be either until we either release a `global` scope in `dendron.yml` or break out `preview` and `publishing` specific config.
> 
> currently, we are doing this to hotfix certain elements of publishing (eg. backlinks on published pages with collections: https://www.kevinslin.com/notes/r4RrLx4xTM2Sc0yOouLkb/)

Got it. Then it looks good 👍🏼

**Review by jonathanyeung — CHANGES_REQUESTED** [review]

**Review by jonathanyeung — APPROVED** [review]

**Pull request merged**
