### PR TITLE
feat: hashtag & reference autocomplete, and multi-vault autocomplete improvements

### PR DESCRIPTION
**Pull request by SeriousBug**
Provides autocomple for references `![[note]]` and hashtags `#my-tag`.

Displays the vault name next to the completion items.

When generating links, if there are notes with the same name in multiple vaults, then generates a cross-vault link `[[dendron-site://vault/note]]`.

 Also tried to display a preview of the suggested items. My implementation is good as far as I can figure out, but VSCode ignores the preview. Left this in for now.

 This includes all the improvements I had in mind for #887.

Also removes the tag snippet (which generates links like `[[#foo|tags.foo]]`) since we have hashtag support now.

### CODE REVIEW

**Review by kevinslin — CHANGES_REQUESTED** [review]
1) can you rebase from master again? we've made some fixes to the web ui that need to be merged
2) it looks like the compiler is failing when generating the preview. you can see the stack trace in the debugger pane in vscode 

```
{"stack":"Error: Missing compiler for node of type `inlineMath`: `[object Object]`\n    at Of.one [as visit] (/Users/kevinlin/code/dendron/node_modules/remark/node_modules/remark-stringify/lib/macro/one.js:12:7)\n    at Of.all (/Users/kevinlin/code/dendron/node_modules/remark/node_modules/remark-stringify/lib/macro/all.js:14:27)\n    at Of.paragraph (/Users/kevinlin/code/dendron/node_modules/remark/node_modules/remark-stringify/lib/visitors/paragraph.js:6:15)\n    at Of.one [as visit] (/Users/kevinlin/code/dendron/node_modules/remark/node_modules/remark-stringify/lib/macro/one.js:19:30)\n    at Of.block (/Users/kevinlin/code/dendron/node_modules/remark/node_modules/remark-stringify/lib/macro/block.js:56:22)\n    at Of.root (/Users/kevinlin/code/dendron/node_modules/remark/node_modules/remark-stringify/lib/visitors/root.js:10:18)\n    at Of.<anonymous> (/Users/kevinlin/code/dendron/node_modules/remark-abbr/dist/index.js:163:45)\n    at Of.one [as visit] (/Users/kevinlin/code/dendron/node_modules/remark/node_modules/remark-stringify/lib/macro/one.js:19:30)\n    at Of.compile (/Users/kevinlin/code/dendron/node_modules/remark/node_modules/remark-stringify/lib/macro/compile.js:9:15)\n    at Function.stringify (/Users/kevinlin/code/dendron/node_modules/unified/index.js:334:39)\n    at convertNoteRefHelperAST (/Users/kevinlin/code/dendron/packages/engine-server/src/markdown/remark/noteRefsV2.ts:647:26)\n    at /Users/kevinlin/code/dendron/packages/engine-server/src/markdown/remark/noteRefsV2.ts:377:31\n    at Array.map (<anonymous>)\n    at Object.convertNoteRefASTV2 (/Users/kevinlin/code/dendron/packages/engine-server/src/markdown/remark/noteRefsV2.ts:355:34)\n    at /Users/kevinlin/code/dendron/packages/engine-server/src/markdown/remark/dendronPub.ts:201:26\n    at node (\u001b[33mrefLinkV2\u001b[39m) (/Users/kevinlin/code/dendron/node_modules/unist-util-visit-parents/index.js:56:27)\n    at node (\u001b[33mparagraph\u001b[39m) (/Users/kevinlin/code/dendron/node_modules/unist-util-visit-parents/index.js:67:75)\n    at node (\u001b[33mroot\u001b[39m) (/Users/kevinlin/code/dendron/node_modules/unist-util-visit-parents/index.js:67:75)\n    at Object.visitParents [as default] (/Users/kevinlin/code/dendron/node_modules/unist-util-visit-parents/index.js:29:26)\n    at transformer (/Users/kevinlin/code/dendron/packages/engine-server/src/markdown/remark/dendronPub.ts:74:17)\n    at wrapped (/Users/kevinlin/code/dendron/node_modules/trough/wrap.js:25:19)\n    at next (/Users/kevinlin/code/dendron/node_modules/trough/index.js:57:24)\n    at done (/Users/kevinlin/code/dendron/node_modules/trough/wrap.js:55:16)\n    at then (/Users/kevinlin/code/dendron/node_modules/trough/wrap.js:62:5)\n    at wrapped (/Users/kevinlin/code/dendron/node_modules/trough/wrap.js:45:9)\n    at next (/Users/kevinlin/code/dendron/node_modules/trough/index.js:57:24)\n    at Object.run (/Users/kevinlin/code/dendron/node_modules/trough/index.js:31:10)\n    at executor (/Users/kevinlin/code/dendron/node_modules/unified/index.js:288:20)\n    at Function.run (/Users/kevinlin/code/dendron/node_modules/unified/index.js:285:5)\n    at pipelineRun (/Users/kevinlin/code/dendron/node_modules/unified/index.js:27:5)\n    at wrapped (/Users/kevinlin/code/dendron/node_modules/trough/wrap.js:25:19)\n    at next (/Users/kevinlin/code/dendron/node_modules/trough/index.js:57:24)\n    at done (/Users/kevinlin/code/dendron/node_modules/trough/wrap.js:55:16)\n    at then (/Users/kevinlin/code/dendron/node_modules/trough/wrap.js:62:5)\n    at wrapped (/Users/kevinlin/code/dendron/node_modules/trough/wrap.js:45:9)\n    at next (/Users/kevinlin/code/dendron/node_modules/trough/index.js:57:24)\n    at Object.run (/Users/kevinlin/code/dendron/node_modules/trough/index.js:31:10)\n    at executor (/Users/kevinlin/code/dendron/node_modules/unified/index.js:358:16)\n    at new Promise (<anonymous>)\n    at Function.process (/Users/kevinlin/code/dendron/node_modules/unified/index.js:350:14)\n    at Object.resolveCompletionItem (/Users/kevinlin/code/dendron/packages/plugin-core/src/features/completionProvider.ts:191:31)\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:172067\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:64:11884\n    at new Promise (<anonymous>)\n    at Object.g [as asPromise] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:64:11856)\n    at F.resolveCompletionItem (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:172038)\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:191093\n    at ze._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:181033)\n    at ze.$resolveCompletionItem (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:191069)\n    at d._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:12815)\n    at d._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:12507)\n    at d._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:11108)\n    at d._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:9960)\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:8064\n    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1835)\n    at E.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15634)\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:29816\n    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1835)\n    at E.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15634)\n    at t._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:20892)\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:17778\n    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1835)\n    at c.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12995)\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12343\n    at Socket.b (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:13287)\n    at Socket.emit (events.js:315:20)\n    at Socket.emit (domain.js:467:12)\n    at addChunk (internal/streams/readable.js:309:12)\n    at readableAddChunk (internal/streams/readable.js:284:9)\n    at Socket.push (internal/streams/readable.js:223:10)\n    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)\n    at Pipe.callbackTrampoline (internal/async_hooks.js:131:14)","message":"Missing compiler for node of type `inlineMath`: `[object Object]`","name":"25:1-25:9","reason":"Missing compiler for node of type `inlineMath`: `[object Object]`","line":25,"column":1,"location":{"start":{"line":25,"column":1,"offset":181},"end":{"line":25,"column":9,"offset":189},"indent":[]},"source":null,"ruleId":null,"fatal":true}
```

**Comment by SeriousBug** [comment]
@kevinslin I'm having trouble running the preview:

In `test-workspace` with the engine running in a shell, the Preview V2 window is completely empty. The engine logs:

```json
{
   "ctx" : "appModule:start",
   "hostname" : "bugmaster",
   "level" : 30,
   "msg" : "redirecting",
   "name" : "dendron.server",
   "pid" : 1245838,
   "redirectUrl" : "http://localhost:3000/vscode/note-preview?ws=%2Fhome%2Fkaan%2FProjects%2FDendron%2Fdendron%2Ftest-workspace&port=3005",
   "time" : 1626720958922
}
```

The plugin logs:

```json
{"level":30,"time":1626720958843,"pid":1245903,"hostname":"bugmaster","name":"dendron","ctx":"dendron.showPreviewV2:run","msg":"pre-execute"}
{"level":30,"time":1626720958844,"pid":1245903,"hostname":"bugmaster","name":"dendron","ctx":"genHTML","view":"dendron.note-preview","src":"http://localhost:3005/vscode/note-preview?ws=%2Fhome%2Fkaan%2FProjects%2FDendron%2Fdendron%2Ftest-workspace&port=3005"}
{"level":30,"time":1626720958845,"pid":1245903,"hostname":"bugmaster","name":"dendron","ctx":"dendron.showPreviewV2:run","msg":"post-execute"}
```

In any other workspace, the Preview V2 window says `Cannot GET /vscode/note-preview.html`. The plugin logs:

```json
{"level":30,"time":1626721121866,"pid":1246622,"hostname":"bugmaster","name":"dendron","ctx":"dendron.showPreviewV2:run","msg":"pre-execute"}
{"level":30,"time":1626721121867,"pid":1246622,"hostname":"bugmaster","name":"dendron","ctx":"genHTML","view":"dendron.note-preview","src":"http://localhost:36979/vscode/note-preview.html?ws=%2Fhome%2Fkaan%2FProjects%2FDendron%2Forg-workspace&port=36979"}
{"level":30,"time":1626721121867,"pid":1246622,"hostname":"bugmaster","name":"dendron","ctx":"dendron.showPreviewV2:run","msg":"post-execute"}
```

And the server logs:

```
GET /vscode/note-preview.html?ws=%2Fhome%2Fkaan%2FProjects%2FDendron%2Forg-workspace&port=36979 404 0.980 ms - 163 - -
```

The built-in VSCode preview works fine in both cases. Any thoughts what might be wrong?

**Comment by kevinslin** [comment]
it only works if you use the test-workspace and start the next-server (see
next server dev docs)

**Comment by SeriousBug** [comment]
Thanks for that. I don't see any errors in the debug console, plugin logs, engine, or anywhere else. Are you seeing that error in any specific note?

**Comment by kevinslin** [comment]
Should have been more specific. It happens in the vscode that the code is in and when you autocomplete a note with math in it. See this loom -> https://www.loom.com/share/791121277edf4d27b84f757d5309c95f

**Comment by SeriousBug** [comment]
@kevinslin This is ready for review now. I fixed the issue you found.

**Comment by kevinslin** [comment]
Looks like there's still an issue with note refs. See this loom https://www.loom.com/share/a4db9b410efa410e9c4b17941aad918b

Can we add more descriptions in the error message? If this is a bigger change, we can add this as an internal improvement item for triage next week

**Comment by SeriousBug** [comment]
I don't see the error message with `dendron.ref.markdown` anymore, but I see it with `dendron.apples` and `dendron.boy`. I think it has something to do with the template stuff (`{{fm.title}}`) in `dendron.boy`.

In any case, I think it's better to merge this PR and work on this issue separately. I especially suspect that this issue is caused by V4-V5 conflicts and will be resolved once we migrate to the new `proc`. I'll put this in triage, and I can also disable the "preview notes during autocomplete" if you'd like.

**Comment by kevinslin** [comment]
Sounds good, lets disable the preview for now since its not working and have a followup triage item

**Comment by SeriousBug** [comment]
Got it, disabled.

**Review by kevinslin — APPROVED** [review]

**Pull request merged**
