### PR TITLE
enhance(workspace): automatically update configuration for vaults that have remotes, but aren't configured as such

### PR DESCRIPTION
**Pull request by SeriousBug**
If a vault has a remote configured, but the vault configuration did not have a remote set, then this PR automatically updates the configuration to mark the vault as a remote vault.

The PR also adds telemetry for both this feature, and also the existing features that fix missing root note and schemas.

Finally, the PR improves our git wrapper when detecting the current remote. Before we would just use the first remote available, but that might not be the remote for the current branch. The new code tries to parse the remote from the upstream of the current branch, then falls back to the first available remote if that fails.

Docs: https://github.com/dendronhq/dendron-site/pull/418

# Dendron Extended PR Checklist

### Basics

- [x] code should follow [Code Conventions](dev.process.code)
- [x] circular dependency check: make sure your code is not introducing new circular dependencies in plugin-core.  See [Avoiding Circular Dependencies](dev.process.code.best-practices).
  - No change
- [x] sticking to existing conventions instead of creating new ones 
  - eg: [if configuration for utilities are already in one module or package, add future utilities there as well](https://github.com/dendronhq/dendron/pull/1960#discussion_r786228021)

### Extended

- General
  - [x] check whether code be simplified
  - [x] check if similar function already exist in the codebase. if so, can it be re-used?
  - [x] check if this change adversely impact performance
    - Minimal, in the most common case this will only check if a single file exists during initialization
- Operations
  - [x] when shipping this change, will it just work or will it introduce additional operational overhead due to complicated interface or known bugs?
    - Considered edge cases, and the action only works if we're sure that the user has a repo with a remote set. Fully automatic so no confusing interface.
- Architecture
  - [~] check if code is introducing changes on a foundational class or interface. if so, call for design review if needed 
    - eg: [making changes to DNode](https://github.com/dendronhq/dendron/pull/2158#pullrequestreview-854689586)

### Basics

- [x] if you are adding analytics related changes, make sure the [Telemetry](https://wiki.dendron.so/notes/84df871b-9442-42fd-b4c3-0024e35b5f3c.html) docs are updated
  - linked above

### Extended

- [x] can we track the performance of this change to know if it is _successful_? 
  - eg: [see usage for export pod](https://github.com/dendronhq/dendron/pull/2190#pullrequestreview-855715612)
    - telemetry above tracks usage

### Basics

- [x] [Write Tests](dev.process.qa.test) 
- [x] [Confirm existing tests pass](dev.process.qa.test)
- [x] [Confirm manual testing](dev.process.qa.test) 
- [x] Common cases tested
- [x] 1-2 Edge cases tested
- [~] If your tests changes an existing snapshot, snapshots have been [updated](dev.process.qa.test)

### Extended

- [ ] If you are adding a new language feature (graphically visible in VS Code/preview/publishing), an example is included in the [test workspace](dev.ref.test-workspace)

- [~] CSS
  - [ ] display is correct for following dimensions
    - [ ] sm: screen ≥ 576px, eg. iphonex, (375x812)
    - [ ] lg: screen ≥ 992px
    - [ ] xxl: screen ≥ 1600px eg. mac (1600x900)
  - [ ] display is correct for following browsers (across the various dimensions)
    - [ ] safari
    - [ ] firefox
    - [ ] chrome

### Basics

- [x] if your change reflects documentation changes, also submit a PR to [dendron-site](https://github.com/dendronhq/dendron-site) and mention the doc PR link in your current PR
  - linked above

## 

### Basics

- [~] does this change introduce a new or better way of doing things that others need to be aware of? if so, an async should be created and a process added in [Development](dev) or [Packages](pkg)

## 

### Extended

- [~]  is this a developer BREAKING change? if another person cloning from this branch will need to adjust their dependencies or mental model of the architecture, then it is. if this is the case, make sure this is communicated according to [Close Loop](dev.process.close-loop)
  - eg. [breaking dev change due to new dependency](https://github.com/dendronhq/dendron/pull/2188#pullrequestreview-855696330)

### CODE REVIEW

**Review by kevinslin — CHANGES_REQUESTED** [review]
can we make this a doctor command and show a dialogue box to ask people to fix it? a little nervous about auto-fixes as we've been having issues with them in the past. 

in general, a design philosophy we might adapt from python: "explicit is better than implicit"

**Comment by jonathanyeung** [comment]
Echo @kevinslin's comments - rather than having this be a part of `ReloadIndex`, let's put this under doctor - @hikchoi and I were discussing last week the prospect of having a scan-for-potential-issues that runs on ext upgrade that runs multiple doctor checks (not fixes) and then provides a summary of issues to users, it makes sense to add this remote check to be a part of that conversation (we were starting to get a bit weary of notification bombing our users on start up).  

Does having an incorrect remote config block the user from properly upgrading to a standalone vault setup?

**Comment by hikchoi** [comment]
Agree on both @kevinslin and @jonathanyeung's points. We have been running into issues of running automatic fixes during activation. Our current way to tackle that is to be explicit about what is about to change (if the user accepts), and I think this is generally a good way forward. We will at some point run into _too many toast notifications_ during the activation lifecycle, but for now what we have will not be overcrowding; most of these potential issue scans twon't happen all at the same time.

@jonathanyeung and I briefly discussed on using a startup welcome view (or the dedicated dendron side panel we have been discussing) to consolidate all detected issues and presenting it nicely in one place, but this is a bit over-engineered for what we have currently. For now, the 80/20 solution would be making this a doctor command, and warning them on activation if detected. The keybinding resolution that we currently do during activation will be changed to follow this pattern as well.

See [findIncompatibleExtensions](https://github.com/dendronhq/dendron/blob/master/packages/plugin-core/src/commands/Doctor.ts#L341:L352) for an example of this

**Comment by SeriousBug** [comment]
Thanks for the feedback everyone. Automatic conversion was something that was discussed briefly months ago that I had in my backlog. I converted this to a Doctor command instead.

I left the existing "create missing root note or schema" behavior, but also kept my changes which make it concurrent and add analytics for them. I can also revert those changes if desired.

Having a welcome screen where we can display issues and more sounds like a good idea, and I agree a doctor action is good until then.

**Review by jonathanyeung — APPROVED** [review]

**Review by kevinslin — APPROVED** [review]

**Pull request merged**
