### PR TITLE
chore: avoid workspace watcher crashing if folder is deleted

### PR DESCRIPTION
**Pull request by SeriousBug**
`WorkspaceWatcher` was using the deprecated `WorkspaceService.isPathInWorkspace` to check if something is in workspace. This function does `this.config`, which runs `WorkspaceService.getOrCreateConfig`, which will attempt to read the config file, or write it if the config file is missing.

If the folder that should contain the config file is missing, this will cause a `ENOENT` error.
I think this can happen if the user loads up a Dendron workspace, but then deletes the folder that contains the workspace while VSCode is still running.

### CODE REVIEW

**Comment by kevinslin** [comment]
looks like a build error

**Comment by SeriousBug** [comment]
My bad, fixed now.

**Review by hikchoi — COMMENTED** [review]
Is there a reason we are fixing the deprecated method instead of the new method?

**Comment by jonathanyeung** [comment]
> Is there a reason we are fixing the deprecated method instead of the new method?

Looks like there are 12 references to the deprecated method.  Could we try to migrate those instances instead? Then, we can also clean up `IWorkspaceService`

**Comment by SeriousBug** [comment]
My bad, I was trying to fix the issue causing the overload of errors in our logs and tried to make the fix as quickly as possible.

The deprecated function is fully removed now.

**Comment by SeriousBug** [comment]
This PR drops the total circular dependency count from 136 to 123.

**Review by kevinslin — APPROVED** [review]

**Pull request merged**
