### PR TITLE
feat: rename header command

### PR DESCRIPTION
**Pull request by SeriousBug**
Adds the rename header command. The command works with both wikilinks and references, including range references (`![[foo#start:#end]]`). It also correctly handles headers that include block anchors or wikilinks (`## foo [[bar|my.bar]] baz`).

### CODE REVIEW

**Comment by SeriousBug** [comment]
#421 #370 #189

**Review by kevinslin — CHANGES_REQUESTED** [review]
this looks good. one addition: currently our heads usually have an alias associated with it because that's the default behavior of `CopyNoteLink`. when renaming a header link, if the alias is the same as the header, lets also rename the alias to the new header

**Comment by kevinslin** [comment]
Looks like there's an error from the alias being undefined

**Comment by SeriousBug** [comment]
Sorry I was still working on it, I'll let you know when it's ready for review.

**Review by kevinslin — APPROVED** [review]

**Comment by kevinslin** [comment]
Looks good. Can you resolve the merge conflict? feel free to merge afterwards

**Pull request merged**
