### PR TITLE
chore: hook for soft warning on circular dependency

### PR DESCRIPTION
**Pull request by jonathanyeung**
## chore(internal): hook for soft warning on circular dependency

BREAKING: adds madge as a dev-dependency; requires madge installation in your local dev environment

Simple hook for now to add warning text to the husky hook with a madge report on the count of circular dependencies. Adding a delta is a bit more involved (need to modify local git state), so I'll defer on that for now.

---

# Pull Request Checklist

If this is your first time submitting a pull request to Dendron, copy and paste the full [Dendron Review Checklist](https://docs.dendron.so/notes/1EoNIXzgmhgagqcAo9nDn.html) into this request and check off each item as necessary. 

This template contains the short checklist which is used by the Dendron core team. 

## Testing
- [ ] [Write Tests](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro.html#writing-tests) 
- [ ] [Confirm existing tests pass](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro.html#executing-tests)
- [ ] [Confirm manual testing](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro.html#manual-testing) 
- [ ] If your tests changes an existing snapshot, make sure that snapshots are [updated](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro.html#updating-test-snapshots)
- [ ] If you are adding a new language feature (graphically visible in VS Code/preview/publishing), make sure that it is included in the [test workspace](https://docs.dendron.so/notes/dtMsF12SF2SUhLN10sYe2.html)
### Docs
- [ ] if your change reflects documentation changes, also submit a PR to [dendron-site](https://github.com/dendronhq/dendron-site) and mention the doc PR link in your current PR
### Analytics
- [ ] if you are adding analytics related changes, make sure the [Telemetry](https://docs.dendron.so/notes/84df871b-9442-42fd-b4c3-0024e35b5f3c.html) docs are updated

### CODE REVIEW

**Review by hikchoi — COMMENTED** [review]
Looks good.

I started doing this manually for all the PRs I make.

1. after I'm done working on stuff, checkout master
2. pull in latest master
3. run the madge command against master
4. checkout my branch
5. rebase to master (we should be doing this anyways because ci is caching our packages and without a rebase we might fail the ci)
6. run the madge command against my branch
7. compare the report count

So in addition to the warning message here, maybe it would be useful to add an npm script that we can run through `Tasks: Run Task` (like our `gen:config` or `Generate JSON Schema`), and add to the warning message that we should be doing the above steps. Extra useful if the output is copied to clipboard but that needs some cross platform shenanigans to work properly for everyone so this should be good enough 😄

**Review by kevinslin — CHANGES_REQUESTED** [review]
1. looks like this is a breaking change for dev (in the sense that when I run it, it will fail if madge isn't installed).
    For dev related breaking changes, can we do the following?
    - mark it as `BREAKING`
        ```
        chore(internal): add circ dep checker

        BREAKING: requires madge to be installed
        ```
    - can you add a new note inside `dendron.docs` under `dev.process.close-loop` and setup a process for how we close the loop on `BREAKING` internal changes?
        - we can later expand this to also add features and other processes as well
2. notice that this was `pre-commit`. are we sure this is where we want it (vs `pre-push`) since it directly impacts the dev workflow? 
3. to close the loop on this, we should also do the following
    - update [[PR Checklist|dendron://dendron.docs/dev.process.review.checklist]]
    - make an announcement in the `#dev` channel about this

**Comment by jonathanyeung** [comment]
> 1. looks like this is a breaking change for dev (in the sense that when I run it, it will fail if madge isn't installed).
>    For dev related breaking changes, can we do the following?
>    
>    * mark it as `BREAKING`
>      ```
>      chore(internal): add circ dep checker
>      
>      BREAKING: requires madge to be installed
>      ```
>    * can you add a new note inside `dendron.docs` under `dev.process.close-loop` and setup a process for how we close the loop on `BREAKING` internal changes?
>      
>      * we can later expand this to also add features and other processes as well
> 2. notice that this was `pre-commit`. are we sure this is where we want it (vs `pre-push`) since it directly impacts the dev workflow?
> 3. to close the loop on this, we should also do the following
>    
>    * update [[PR Checklist|dendron://dendron.docs/dev.process.review.checklist]]
>    * make an announcement in the `#dev` channel about this

1. updated the PR description, will add to commit message of merge commit when this is merged.
2. On second thought, push is probably better / less intrusive.
3. I can make the announcement after merge. Dendron Docs Updates: https://github.com/dendronhq/dendron-docs/commit/16d561a7aac634b64efa76ef21ac99b2e42dfdaf

**Comment by jonathanyeung** [comment]
> maybe it would be useful to add an npm script that we can run through Tasks: Run Task
> Do you think it's worth mentioning this in the PR template? (especially for external contributors)

@hikchoi - good suggestions. Lemme add a vs code task as a next; I've updated the PR template and also added a link in the husky hook console log to this note which I just added: https://docs.dendron.so/notes/773e0b5a-510f-4c21-acf4-2d1ab3ed741e/#avoiding-circular-dependencies

**Review by kevinslin — APPROVED** [review]

**Comment by kevinslin** [comment]
looks good, we might want to update the documentation in dendron-docs to mention that we want folks to copy the output of the pre-commit hook into the review (vs just running madge)

**Pull request merged**
