### PR TITLE
fix: title wrap and hamburger offset on mobile

### PR DESCRIPTION
**Pull request by pvorona**
- Fix title wrap on mobile
- Fix hamburger button offset on mobile

https://github.com/dendronhq/dendron/issues/2159

Video:
https://drive.google.com/file/d/1vCqYasHUxp6ZvB4aAlmq7HIvvpEJWfmz/view?usp=sharing

https://drive.google.com/file/d/1PZt3kOkrbFJIM5lsz7UjaFd8cutvzrBy/view?usp=sharing

# Pull Request Checklist

If this is your first time submitting a pull request to Dendron, copy and paste the full [Dendron Review Checklist](https://docs.dendron.so/notes/1EoNIXzgmhgagqcAo9nDn.html) into this request and check off each item as necessary. 

This template contains the short checklist which is used by the Dendron core team. 

## Testing
- [ ] [Write Tests](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro.html#writing-tests) 
- [ ] [Confirm existing tests pass](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro.html#executing-tests)
- [x] [Confirm manual testing](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro.html#manual-testing) 
- [ ] If your tests changes an existing snapshot, make sure that snapshots are [updated](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro.html#updating-test-snapshots)
- [ ] If you are adding a new language feature (graphically visible in VS Code/preview/publishing), make sure that it is included in the [test workspace](https://docs.dendron.so/notes/dtMsF12SF2SUhLN10sYe2.html)
### Docs
- [ ] if your change reflects documentation changes, also submit a PR to [dendron-site](https://github.com/dendronhq/dendron-site) and mention the doc PR link in your current PR
### Analytics
- [ ] if you are adding analytics related changes, make sure the [Telemetry](https://docs.dendron.so/notes/84df871b-9442-42fd-b4c3-0024e35b5f3c.html) docs are updated

### CODE REVIEW

**Comment by kevinslin** [comment]
thanks for the issue - can you also sign our CLA to appease the CLA bot?

**Comment by pavel-remo** [comment]
@kevinslin done.

**Comment by kevinslin** [comment]
can you rebase to remove merge conflict? otherwise, lgtm

**Comment by pvorona** [comment]
@kevinslin done

**Pull request merged**
