### PR TITLE
enhance(plugin-core): fill in current hierarchy for Move Header

### PR DESCRIPTION
**Pull request by saifahn**
Related to #2238

I wasn't sure about the tests - I couldn't get the integration tests for the `MoveHeader.test.ts` to progress - it seems like it fails at an assertion that seems to take time and is repeated on the CI until it passes? Is this related to using the old testing utils?

EDIT: I noticed that the tests are failing for the plugin on the CI, I'll have to take a look at that too.

If there are any pointers on how to get this to work, I can have a go at writing a test for this. 

https://user-images.githubusercontent.com/9913851/186452753-232d5a03-a904-4f4e-b438-da1c5ed40526.mp4

## Commit

- [x] make sure your branch names adhere to our [branch style](https://docs.dendron.so/notes/adc39825-77a6-46cf-9c49-2642fcb4248e)
- [x] make sure the commit message follows Dendron's [commit style](https://docs.dendron.so/notes/QN46JTSWpEkDkr94TJ85w)
- [x] if this pull request is addressing an existing issue, make sure to link this PR to the issue that it is resolving.
  - NOTE: make sure to read [Addressing open issues](https://docs.dendron.so/notes/adc39825-77a6-46cf-9c49-2642fcb4248e)

## Code

- [x] code should follow [Code Conventions](https://docs.dendron.so/notes/773e0b5a-510f-4c21-acf4-2d1ab3ed741e)
- [x] sticking to existing conventions instead of creating new ones 

## Tests

- [ ] [Write Tests](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro) 
- [ ] [Confirm existing tests pass](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro)
- [ ] [Confirm manual testing](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro) 
- [ ] Common cases tested
- [ ] 1-2 Edge cases tested
- [ ] If your tests changes an existing [snapshot](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro)
  - [ ] [Update the Snapshot](https://docs.dendron.so/notes/u7utw5w8gyacuh3ok9ehi8j)

## Docs

- ~~[ ] if your change reflects documentation changes, also submit a PR to [dendron-site](https://github.com/dendronhq/dendron-site) and mention the doc PR link in your current PR (NOTE: submit the PR against the `dev` branch of the dendron-site repo)~~
- ~~[ ] does this change introduce a new or better way of doing things that others need to be aware of? if so, an async should be created and a process added in [Development](https://wiki.dendron.so/notes/ce9b9b29-d85b-492b-b76d-5e0c5dc52b03) or [Packages](https://wiki.dendron.so/notes/ok9ifke0zsfxnnh7xog79z5)~~

### CODE REVIEW

**Comment by kevinslin** [comment]
> Related to #2238
> 
> I wasn't sure about the tests - I couldn't get the integration tests for the `MoveHeader.test.ts` to progress - it seems like it fails at an assertion that seems to take time and is repeated on the CI until it passes? Is this related to using the old testing utils?
> 
> EDIT: I noticed that the tests are failing for the plugin on the CI, I'll have to take a look at that too.
> 
> If there are any pointers on how to get this to work, I can have a go at writing a test for this.
> Kapture.2022-08-20.at.17.43.05.mp4
> ## Commit
> 
>     * [x]  make sure your branch names adhere to our [branch style](https://docs.dendron.so/notes/adc39825-77a6-46cf-9c49-2642fcb4248e)
> 
>     * [x]  make sure the commit message follows Dendron's [commit style](https://docs.dendron.so/notes/QN46JTSWpEkDkr94TJ85w)
> 
>     * [x]  if this pull request is addressing an existing issue, make sure to link this PR to the issue that it is resolving.
>       
>       * NOTE: make sure to read [Addressing open issues](https://docs.dendron.so/notes/adc39825-77a6-46cf-9c49-2642fcb4248e)
> 
> 
> ## Code
> 
>     * [x]  code should follow [Code Conventions](https://docs.dendron.so/notes/773e0b5a-510f-4c21-acf4-2d1ab3ed741e)
> 
>     * [x]  sticking to existing conventions instead of creating new ones
> 
> 
> ## Tests
> 
>     * [ ]  [Write Tests](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro)
> 
>     * [ ]  [Confirm existing tests pass](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro)
> 
>     * [ ]  [Confirm manual testing](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro)
> 
>     * [ ]  Common cases tested
> 
>     * [ ]  1-2 Edge cases tested
> 
>     * [ ]  If your tests changes an existing [snapshot](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro)
>       
>       * [ ]  [Update the Snapshot](https://docs.dendron.so/notes/u7utw5w8gyacuh3ok9ehi8j)
> 
> 
> ## Docs
> 
>     * ~[ ] if your change reflects documentation changes, also submit a PR to [dendron-site](https://github.com/dendronhq/dendron-site) and mention the doc PR link in your current PR (NOTE: submit the PR against the `dev` branch of the dendron-site repo)~
> 
>     * ~[ ] does this change introduce a new or better way of doing things that others need to be aware of? if so, an async should be created and a process added in [Development](https://wiki.dendron.so/notes/ce9b9b29-d85b-492b-b76d-5e0c5dc52b03) or [Packages](https://wiki.dendron.so/notes/ok9ifke0zsfxnnh7xog79z5)~

yeah, this is due to `moveheader` being on the old test harness. the easiest way to fix the error is to stub `getInitialValueFromOpenEditor`
see [stubs](https://docs.dendron.so/notes/pkzdogzfyracy9lnc1165u2)
[[dendron://dendron.docs/dev.process.qa.test.cook.stubbing]]

```ts
notePickerStub = sinon.stub(NotePickerUtils, 'getInitialValueFromOpenEditor')
```
you should be able to test that this is set correctly using the spy interface

```ts
expect(notePickerStub.calledWith(...)).toBeTruthy()
```

**Comment by saifahn** [comment]
Thanks, I'll try and take a look some time this week

**Comment by saifahn** [comment]
Thanks for the tip! I ended up removing the `initialValue` property from `CommandInput`as it should be no longer used as the initialValue is taken from the open editor. It has been removed from the tests in favour of stubbing the values instead.

I did think it was a bit strange to be checking based on initial value, whereas it would probably be ideal if the tests were also able to input new characters for the destination instead... but I couldn't figure out a way to do this easily.

I've just realised that I didn't write an explicit test for the new behaviour, so I'll work on that next chance I get.
Any feedback on the changes so far would be appreciated if you happen to have the time to look 🙇

**Comment by kevinslin** [comment]
> Thanks for the tip! I ended up removing the `initialValue` property from `CommandInput`as it should be no longer used as the initialValue is taken from the open editor. It has been removed from the tests in favour of stubbing the values instead.
> 
> I did think it was a bit strange to be checking based on initial value, whereas it would probably be ideal if the tests were also able to input new characters for the destination instead... but I couldn't figure out a way to do this easily.
> 
> I've just realised that I didn't write an explicit test for the new behaviour, so I'll work on that next chance I get. Any feedback on the changes so far would be appreciated if you happen to have the time to look 🙇

this looks good. for testing this case without stubbing, you can open the current note by following the example [here](https://docs.dendron.so/notes/jtHIVXVpyHwRiq3tJBbfq#opening-a-note-programatically-in-the-current-editor)

**Comment by saifahn** [comment]
The code was already opening the origin note in the `onInitFunc`defined in the "WHEN header is selected" describe block's `beforeEach` function.

I've updated this to use WSUtilsV2 instead of the previous deprecated version. I've used this to check that the new test will be prefilled with the origin note's `fname` when MoveHeaderCommand's `gatherInputs` is called.

However, I was wondering for the other tests, is there a way to open the prompt and then type in the new text for the destination? I thought that would be a more accurate representation for the flow a user would go through when using the command. I couldn't quite figure out how to achieve this, though.

Or is this something that we don't use within the integration tests? If not, then maybe the PR is ready to have a look at in its current state (if the CI tests pass).

**Comment by kevinslin** [comment]
got i

> Thanks, the code was already opening the origin note in the `onInitFunc` defined in the "WHEN header is selected" describe block's `beforeEach` function.
> 
> I've updated this to use WSUtilsV2 instead of the previous deprecated version. I've used this to check that the new test will be prefilled with the origin note's `fname` when MoveHeaderCommand's `gatherInputs` is called.
> 
> However, I was wondering for the other tests, is there a way to open the prompt and then type in the new text for the destination? I thought that would be a more accurate representation for the flow a user would go through when using the command. I couldn't quite figure out how to achieve this, though.
> 
> Or is this something that we don't use within the integration tests? If not, then maybe the PR is ready to have a look at in its current state (if the CI tests pass).
> 
> EDIT: The integration tests and other tests pass locally (on MacOS, node v16.15.1), so I'm not sure what's happening with the CI tests - is this normal?

got it - you're good then! we currently have a few flaky tests that @jonathanyeung will be squashing the coming weeks so your code is good to merge! thanks for PR :)

**Pull request merged**
