### PR TITLE
fix: segment track cleanup

### PR DESCRIPTION
**Pull request by hikchoi**
# fix: segment track cleanup
This PR:
- Fixes `genConfig` to generate contribution points in `package.json` to only contain properties that vscode define.
- Removes a redundant `setupSegmentClient` call
- Removes properties in `CommandEntry` that were used to generate `dendron.cheatsheet` note from jinja template.
- Corrects the `when` clause for displaying `Dendron: Delete Node` in explorer/context
- Adds `when` clause to all views that are not functional when the user is not in a workspace that dendron recognizes.
- Adds `when` clause to all commands that are not functional when the user is not in a workspace that dendron recognizes.
  - This is to reduce clutter in the command palette and also to avoid confusion to users that are new to Dendron and as yet to initialize a Dendron workspace.
  - This will also prevent a significant amount of error reporting since most of the non-functional commands will cause an `engine not set` error or similar.
  - The only commands that will be available in the command palette when in a non-dendron workspace will be the following:
    - `Dendron: Launch Tutorial` 
    - `Dendron: Initialize Workspace`
    - `Dendron: Change Workspace`
    - `Dendron: Enable Telemetry`
    - `Dendron: Disable Telemetry`
    - `Dendron: Sign Up`
    - `Dendron: Sign In`
    - `Dendron: Contribute`
    - `Dendron: Show Help`
    - `Dendron:Dev: Open Logs`

# Pull Request Checklist

If this is your first time submitting a pull request to Dendron, copy and paste the full [Dendron Review Checklist](https://docs.dendron.so/notes/1EoNIXzgmhgagqcAo9nDn.html) into this request and check off each item as necessary. 

This template contains the short checklist which is used by the Dendron core team. 

## Testing
- [ ] [Write Tests](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro.html#writing-tests) 
- [x] [Confirm existing tests pass](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro.html#executing-tests)
- [x] [Confirm manual testing](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro.html#manual-testing) 
- [ ] If your tests changes an existing snapshot, make sure that snapshots are [updated](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro.html#updating-test-snapshots)
- [ ] If you are adding a new language feature (graphically visible in VS Code/preview/publishing), make sure that it is included in the [test workspace](https://docs.dendron.so/notes/dtMsF12SF2SUhLN10sYe2.html)
### Docs
- [ ] if your change reflects documentation changes, also submit a PR to [dendron-site](https://github.com/dendronhq/dendron-site) and mention the doc PR link in your current PR
### Analytics
- [ ] if you are adding analytics related changes, make sure the [Telemetry](https://docs.dendron.so/notes/84df871b-9442-42fd-b4c3-0024e35b5f3c.html) docs are updated

### CODE REVIEW

**Review by jonathanyeung — APPROVED** [review]
LGTM.

> Adds when clause to all commands that are not functional when the user is not in a workspace that dendron recognizes.

This may have significant (positive) impact on helping users be less confused about workspaces and with the error reporting!  Fingers crosssed

**Comment by hikchoi** [comment]
Just noticed that `Dendron: Show Help` links to `dendron.cheatsheet` in our wiki. now that we are not doing this anymore should we remove this command altogether? (and also remove the jinja template and the `gen:cheatsheet` task).

The when clauses have made the `Show Help` command much more visible to users when they are in a non-dendron workspace and I don't think opening a link to a note that has a #prune tag would be ideal

**Comment by jonathanyeung** [comment]
> Just noticed that `Dendron: Show Help` links to `dendron.cheatsheet` in our wiki. now that we are not doing this anymore should we remove this command altogether? (and also remove the jinja template and the `gen:cheatsheet` task).
> 
> The when clauses have made the `Show Help` command much more visible to users when they are in a non-dendron workspace and I don't think opening a link to a note that has a #prune tag would be ideal

Maybe redirect to the FAQ? https://wiki.dendron.so/notes/683740e3-70ce-4a47-a1f4-1f140e80b558/

**Comment by hikchoi** [comment]
> > Just noticed that `Dendron: Show Help` links to `dendron.cheatsheet` in our wiki. now that we are not doing this anymore should we remove this command altogether? (and also remove the jinja template and the `gen:cheatsheet` task).
> > The when clauses have made the `Show Help` command much more visible to users when they are in a non-dendron workspace and I don't think opening a link to a note that has a #prune tag would be ideal
> 
> Maybe redirect to the FAQ? https://wiki.dendron.so/notes/683740e3-70ce-4a47-a1f4-1f140e80b558/

hmm I don't know.. Linking to a collection of random bits of knowledge would confuse a user even further I imagine. This is a command that is very rarely used, and probably something we want to improve in another PR anyways. Disregard my comment.

**Comment by kevinslin** [comment]
@hikchoi yeah, lets add show help in another section. instead of going to a page, we might even want to do something interactive

**Review by kevinslin — APPROVED** [review]

**Comment by hikchoi** [comment]
> @hikchoi yeah, lets add show help in another section. instead of going to a page, we might even want to do something interactive

Yeah I was also considering a web view that can generate something like what the jinja template was originally doing that can interactively help the user.

**Pull request merged**
