### PR TITLE
chore: upgrade next to 11 and allow minor upgrade

### PR DESCRIPTION
**Pull request by viztor**

### CODE REVIEW

**Comment by kevinslin** [comment]
looks like you have some build errors

**Comment by viztor** [comment]
> looks like you have some build errors

I realize test all doesn't test that package.

**Comment by viztor** [comment]
seems next 11 added build time lint, hence the error. might have to fix those listing err later.

**Review by kevinslin — CHANGES_REQUESTED** [review]
Looks like there's an issue with loading in dev mode. See https://www.loom.com/i/c69ddec7f5a64a0d92d436c16f1ca16c

You can repro by following [[Dev|pkg.dendron-next-server.dev]] and running against the browser 

(I used the following string, you'll have to adjust yours based on where Dendron test-workspace is located)

eg. http://localhost:3000/vscode/note-preview?ws=%2FUsers%2Fkevinlin%2Fcode%2Fdendron%2Ftest-workspace&port=3005&browser=1

**Comment by viztor** [comment]
seems to be fixed with the updated Webpack 5 config... 
image

**Review by kevinslin — APPROVED** [review]

**Comment by kevinslin** [comment]
great job. merging!

**Pull request merged**
