### PR TITLE
fix(publish): missing "link to anchor" icon by headings and block anchors

### PR DESCRIPTION
**Pull request by SeriousBug**
This PR restores the link icon that was located by headings and at places where block anchors are attached. The link icons are always visible but are colored the same color as the text. Once the related heading or paragraph is hovered over, the icon will change into the link color for the current theme.

Widescreen:

Small screen:

### CODE REVIEW

**Comment by kevinslin** [comment]
its a little jarring to have the handle show up in every element. can we make it invisible unless the user hovers over it?

**Review by bpathakota — CHANGES_REQUESTED** [review]
Think it would be better if we followed a standardized approach for fix commits - to indicate what issue is being fixed. e.g. `fix(publish): missing link icon by headings and block anchors`

**Comment by SeriousBug** [comment]
@kevinslin Done, it now only appears on hover, but only on devices that can hover (e.g. desktops and laptops). Other devices like smartphones will always display the icons. While that looks a little jarring in the example image, that's because there are tons of anchors in that example. In real world usage most of the time it will only be next to headings.

**Comment by kevinslin** [comment]
> @kevinslin Done, it now only appears on hover, but only on devices that can hover (e.g. desktops and laptops). Other devices like smartphones will always display the icons. While that looks a little jarring in the example image, that's because there are tons of anchors in that example. In real world usage most of the time it will only be next to headings.

can we default to not show on mobile vs show?

**Comment by kevinslin** [comment]
> @kevinslin Sure, but the anchors would be completely unusable on mobile then. Users won't have any way of seeing them.

got it. we'll take that tradeoff for now until we can make it work more unobtrusively on mobile.

**Comment by SeriousBug** [comment]
@kevinslin Sure, done.

**Review by kevinslin — APPROVED** [review]

**Pull request merged**
