### PR TITLE
fix(publish): display headings pleasantly when containing non-textonly content types 

### PR DESCRIPTION
**Pull request by namjul**
- will fix
  - [[dendron://incubator/task.2022.08.07.code-in-heading-breaks-the-formatting]]
  - [[dendron://private/task.2022.08.29.revisit-headings-whitespace]]

# Pull Request Checklist

If you are a community contributor, copy and paste the PR template from [Dendron Community PR Checklist](https://gist.github.com/kevinslin/5d1a6663638259e7dbd33b01975cc00f) and add it to the body of the pull request. 

If you are a team member, copy and paste the template from [Dendron Extended PR Checklist](https://gist.github.com/kevinslin/dfc7a101f21c58478216aa0d70256bc2).

To copy the template, click on the `Raw` button on the gist to copy the plaintext version of the template to this PR.

### CODE REVIEW

**Comment by kevinslin** [comment]
for the ui changes, can we also add playwright tests when this is ready?

**Comment by kevinslin** [comment]
looks like snapshot tests are failing

**Review by hikchoi — CHANGES_REQUESTED** [review]
Just tested it out locally and fixes the issue!

Looks good other than the snapshot fails

**Comment by kevinslin** [comment]
looks like playwright test are failing?

**Comment by namjul** [comment]
> looks like playwright test are failing?

The error https://github.com/dendronhq/dendron/actions/runs/3089152419/jobs/4996433156#step:10:32 gets resolved when I revert https://github.com/dendronhq/dendron/commit/27662dc9de#diff-48c116cf8058e55ab46b8ace6daf7fad4141f3f1e1d1c089b8458ec0135547a3L52-R56. The actuall error happens in `DendronTOC` and possibly conflicts by having antd using 17.x `@types/react` and `DendonTOC` 18.x.

What was the reason we upgraded `@types/react` ?

**Review by hikchoi — CHANGES_REQUESTED** [review]
looks like either we have to revert the `@types/react` version bump, or bump up antd to at least `4.20`, since that is when they fixed the compatibility issue with `@types/react` 18

(antd commit that fixed it I _think_: https://github.com/ant-design/ant-design/commit/5b8e4e51e95c91efe4d57aa08b57fa6401d54111)

Do we have a reason to stick with the current version of antd?

**Comment by kevinslin** [comment]
we can either upgrade antd or downgrade types/react in nextjs. either option works, we might run into subtle differences in rendering if upgrading antd

**Comment by hikchoi** [comment]
There are quite a few minor releases we are jumping up, and I see a lot of deprecations in their releases. Bumping antd up in this PR might be a bit of a scope creep as we don't know what will break yet. 

One vote from me for downgrading the types and revisiting it later in a separate task 🙆🏼

**Comment by namjul** [comment]
@kevinslin @hikchoi I decided to adress this in a seperate PR https://github.com/dendronhq/dendron/pull/3561.

**Review by hikchoi — APPROVED** [review]

**Review by kevinslin — APPROVED** [review]

**Pull request merged**
