### PR TITLE
neverthrow exploration

### PR DESCRIPTION
**Pull request by namjul**

### CODE REVIEW

**Comment by hikchoi** [comment]
Hey @namjul, awesome.
There are still some errors that are failing the tests but I think we can merge this into `chore/iconfigstore` and I can take it from there.

Thanks a lot for the help!

**Comment by hikchoi** [comment]
fyi: continued working the rest in #3748. @namjul

**Comment by hikchoi** [comment]
looks good other than the build error (unless you had other things you were intending to add)

**Comment by namjul** [comment]
>  if you don't have the bandwidth I can take over from here and proceed on Friday. let me know.

I will leave this as is now and let you proceed.
Last thing was playing with a dicriminated error type here https://github.com/dendronhq/dendron/pull/3744/commits/23ac7e5582134f3a63a70fb8db91eb8353bb0109. Not intended to be used anytime soon and rather a experiment/peek into this idea.

**Pull request merged**
