### PR TITLE
fix/for-preview-links-to-navigate-within-the-same-page-in-the-note

### PR DESCRIPTION
**Pull request by nickolay-kondratyev**
fix/for-preview-links-to-navigate-within-the-same-page-in-the-note

## General
This makes the preview links act as navigators for the note, BUT it does not currently navigate within the preview https://www.loom.com/share/24f3f11ac94442e6aacf46dea3e1593c 

### Quality Assurance
- [x] make sure all the existing [tests](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#running-all-tests) pass
- [x] do a spot check by running your feature with our [test workspace](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#test-workspace)
- [ ] after you submit your pull request, check the output of our [integration test](https://github.com/dendronhq/dendron/actions) and make sure all tests pass
  - NOTE: if you running mac/linux, check the windows output and vice versa if you are developing on windows

### CODE REVIEW

**Review by kevinslin — CHANGES_REQUESTED** [review]
1.  is this working for you? when I try to do this locally, I run into an exception thrown by [assertUnreachable](https://github.com/dendronhq/dendron/blob/1ec313e0d38e3353685d859de4bdcb91380217f7/packages/plugin-core/src/commands/ShowPreviewV2.ts#L219-L219)


2.  for any manual test (eg. clicking on the preview link), can you also add an example in `test-workspace`?

see [[PR Checklist|dendron://dendron.dendron-site/dendron.dev.pull-request.checklist#^9jtWc6ov340p]]

**Comment by nickolay-kondratyev** [comment]
Weird that its reaching that assert for you. Looking at code diff the assert is in the outer switch statement which is being modified by this change. Can you reproduce the failure without this commit? 

Here is the change working in test workspace:
https://www.loom.com/share/3c53d2ff4adb43d590ddc4f2b4f05897

**Comment by kevinslin** [comment]
> Weird that its reaching that assert for you. Looking at code diff the assert is in the outer switch statement which is not being modified by this change. Can you reproduce the failure without this commit?
> 
> Here is the change working in test workspace:
> https://www.loom.com/share/3c53d2ff4adb43d590ddc4f2b4f05897

1. What version of VSCode are you using? I'm using 1.60.2 and am getting this issue -> https://www.loom.com/share/3c53d2ff4adb43d590ddc4f2b4f05897

After some digging it looks like regular preview from master also has this issue. If you're not on 1.60.2, can you upgrade and see if you can repro?

 2. Can you make sure to create a manual test in `test-workspace` as part of this commit?
3. no worries about current commits but moving forward,  can you make sure prs  start with `[feat|fix|enhance|]/[{description-of-pr-in-kebab-case}]`
        - `eg. feat/add-thisthing`

**Comment by nickolay-kondratyev** [comment]
1. The loom is a copy of my loom but I did run into assertUnreachable on the master branch as well (looking at the console output) the current commit added a case statement for the new message type so if thats the one you ran into before it should be gone now.

2. Added manual test. [[dendron.links.heading-anchors]] Also in the last commit added a change for the preview to navigate to heading anchor from a different page (that wasn't in as well). 

3. modified the current PR to start with fix/...

**Comment by kevinslin** [comment]
>     1. The loom is a copy of my loom but I did run into assertUnreachable on the master branch as well as you have mentioned (looking at the console output) the current commit added a case statement for the new message type so if thats the one you ran into before it should be gone now.
> 
>     2. Added manual test. [[dendron.links.heading-anchors]]
> 
>     3. modified the current PR to start with fix/...
> 
> 
> Also in the last commit added a change for the preview to navigate to heading anchor from a different page (that wasn't a functionality before as well).
> 
> To note: preview navigation will not work correctly for notes with non standards ids such as notes in `test-workspace` that have ids that are not alphanumeric and are not guidlike since regex will not match ids like 'links.headers' due to it not being alphanumeric.

left comment in https://github.com/dendronhq/dendron/pull/1385

**Review by kevinslin — APPROVED** [review]

**Pull request merged**
