### PR TITLE
chore: streamline common-assets styles

### PR DESCRIPTION
**Pull request by namjul**
This PRs aim is to collect the scattered css styles back into common-all. Specifically this is about scss styles for dendron-plugin-views and nextjs-template. It adds two new scss files `main-next.scss` and `main-plugin.scss` that contain context specific styles and levels out the common styles only back into `main.scss`  (and its dependend files). 

~~The asset sync (distribution of the styles from common-all into views and next) is refactored to only be done from the `dendron dev sync_assets` cli command.~~ After some more understanding with the current setup this would result in a timing issue/circular dependency. The way this works is that first all is built and as the last step assets are getting distributed (bootstrap/scripts/buildAll.js). This seems to be unintitive because you would assume that for building, assets are first needed. But like the timing issue hints at, its both, building requires assets and assets distribution requires certain things to be build. 
Why might want to refactor this to be more straightforward/less confusing/more intuitive.

This PR also removes some unused code found during the implementation.

Update to docs: [[dendron://dendron.docs/pkg.common-assets#style-changes]]

- future improvements
  - refactor for simplicity by way of making things less depend on  each other.
  - improve DX by creating symlinks instead of copies.

# Pull Request Checklist

If you are a community contributor, copy and paste the PR template from [Dendron Community PR Checklist](https://gist.github.com/kevinslin/5d1a6663638259e7dbd33b01975cc00f) and add it to the body of the pull request. 

If you are a team member, copy and paste the template from [Dendron Extended PR Checklist](https://gist.github.com/kevinslin/dfc7a101f21c58478216aa0d70256bc2).

To copy the template, click on the `Raw` button on the gist to copy the plaintext version of the template to this PR.

### CODE REVIEW

**Comment by kevinslin** [comment]
> [CLA assistant check](https://cla-assistant.io/dendronhq/dendron?pullRequest=3562) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dendronhq/dendron?pullRequest=3562) before we can accept your contribution.
> **Samuel Hobl** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dendronhq/dendron?pullRequest=3562) it.

@namjul are you using a different email for this pr? if so, can you make sure to make an offering to the CLA bot?

**Review by hikchoi — APPROVED** [review]
LGTM

nice touch dividing the level-outs to each commits and having the diffs. helped reviewing a lot.

**Review by kevinslin — CHANGES_REQUESTED** [review]
- when building the monorepo, `yarn setup` runs `[[../bootstrap/scripts/buildAll.js]]`. this currently fails when building `dendron-plugin-views` because `main-plugin.scss` is not available (the sync-assets step runs as the very last line of `buildAll.js`, we'll need to switch the order)
- `sync-assets` currently fails with an error looking for `dendron-plugin-views/build/static/js`

**Comment by kevinslin** [comment]
can you rebase to resolve the conflicts?

**Review by kevinslin — APPROVED** [review]
nice job. this will make it much easier to extend style sheets separately!

**Pull request merged**
